### ISSUE TITLE
Where to put these files

### ISSUE THREAD

**Issue by dagwieers** [sparkfun/Fritzing_Parts#12]
It would help if the **README** stated where exactly I have to put these directories and files so Fritzing picks them op. I tried **parts/contrib** and **parts/user,** to no avail.

A small set of hints would be much appreciated.

**Comment by aknoerig** [comment]
Take a look at the freshly refined instructions at [https://github.com/fritzing/fritzing-parts/blob/master/CONTRIBUTING.md](https://github.com/fritzing/fritzing-parts/blob/master/CONTRIBUTING.md).
Hope this answers your question, since it seems to be fritzing generic rather than Sparkfun specific?

**Comment by dagwieers** [comment]
Thanks and true.

But users ending up on your website will also have to perform this operation.
So if I may suggest to add the instructions and a link to the README.md of this project ?
(When looking for answers I came across many inquiries and no concrete answers like yours)

Thanks again !

**Comment by aknoerig** [comment]
@ToniCorinne, could you take care of this?

**Comment by ToniCorinne** [comment]
Added - thanks!

**Comment by dagwieers** [comment]
Thanks a lot !
