### ISSUE TITLE
Connector Labels not showing

### ISSUE THREAD

**Issue by AusUser5** [sparkfun/Fritzing_Parts#13]
Connector Labs are not showing 10617_sfe_lipo_fuel_gauge (

**Comment by bboyho** [comment]
Hi,

By comparing the top view of the physical board to the Fritzing part, the representation for the SparkFun LiPo Fuel Gauge [ [https://www.sparkfun.com/products/10617](https://www.sparkfun.com/products/10617) ] is accurate in the breadboard view:

<div style="text-align:center"><a href="https://cdn.sparkfun.com/assets/parts/5/2/7/9/10617-04.jpg"><img src="https://cdn.sparkfun.com/r/300-300/assets/parts/5/2/7/9/10617-04.jpg" alt="LiPo Fuel Guage Top View"></a></div>

If you begin wiring the part, a text box should pop up below the wire and mouse indicating what pin is connected on the board. I also did not see a problem with the labels in the schematic view.

Based on this information, I do not believe that there is an issue with board's connector labels.
