### ISSUE TITLE
no .fzbz file to import

### ISSUE THREAD

**Issue by MarcusWolschon** [sparkfun/Fritzing_Parts#16]
There is no .fzbz file to import and the README.md doesn't state how exactly to import this part library into Fritzing.

**Comment by MarcusWolschon** [comment]
The linked documentation is idiotic. You don't git checkout anything and then move all part of it somewhere outside the checkout folder. You'd never be able to do a git pull because you have uncommited local changes (deleting all those files) that you can't possibly merge.

**Comment by MarcusWolschon** [comment]
After 1.5 years? How should I still know. 
Probably the Sparkfun AutoDriver V11 and V13 boards to recreate a setup+pinout and render graphics  for user documentation.

**Comment by loricrotser** [comment]
Apologies for the long reply time; this is newly assigned to me. 

I'll see what I can do about getting you that autodriver board in fritzing. I'm assuming you mean the L6470 - let me know if that's not correct. 

Thanks

**Comment by MarcusWolschon** [comment]
Yes, that's the chip on these board revisions.

**Comment by loricrotser** [comment]
Initial checkin of v13:
[https://github.com/sparkfun/Fritzing_Parts/blob/master/products/13752_sfe_autodriver_stepper_motor_v13.fzpz](https://github.com/sparkfun/Fritzing_Parts/blob/master/products/13752_sfe_autodriver_stepper_motor_v13.fzpz)

V10 has been retired - I'll be working on that one next week. 
Thank you for your patience!

**Comment by loricrotser** [comment]
I've just uploaded the initial checkin for v10 of the autodriver: 
[https://github.com/sparkfun/Fritzing_Parts/blob/master/products/11611_sfe_autodriver_stepper_motor_v10.fzpz](https://github.com/sparkfun/Fritzing_Parts/blob/master/products/11611_sfe_autodriver_stepper_motor_v10.fzpz)

Double clicking on the .fzpz will open it in fritzing and import the part. 

I've also logged an internal ticket to look into providing bins for customer fritzing parts. 

Thank you!
