### ISSUE TITLE
missing L6470-AutoDriver

### ISSUE THREAD

**Issue by MarcusWolschon** [sparkfun/Fritzing_Parts#17]
This library is missing the Sparkfun L6470-AutoDriver V10 and V13 boards (different connector pinouts).

**Comment by bboyho** [comment]
Hi,

Sorry for the delay in reply. @loricrotser generated the Fritzing parts for both versions recently. You can find this in the products folder:

* V10 [ [https://github.com/sparkfun/Fritzing_Parts/blob/master/products/11611_sfe_autodriver_stepper_motor_v10.fzpz](https://github.com/sparkfun/Fritzing_Parts/blob/master/products/11611_sfe_autodriver_stepper_motor_v10.fzpz) ]
* v13 [ [https://github.com/sparkfun/Fritzing_Parts/blob/master/products/13752_sfe_autodriver_stepper_motor_v13.fzpz](https://github.com/sparkfun/Fritzing_Parts/blob/master/products/13752_sfe_autodriver_stepper_motor_v13.fzpz) ]
