### ISSUE TITLE
Errors in "BOB-12009 Bi-Directional Logic Level Converter.fzpz" part

### ISSUE THREAD

**Issue by afa-** [sparkfun/Fritzing_Parts#2]
Hi,

There are errors in the part " Fritzing_Parts / Products / Breakout Boards / BOB-12009 Bi-Directional Logic Level Converter.fzpz". The pins in the schematic view are incorrect. 

Thanks.

**Comment by hello-techie** [comment]
Wonderful, thank you! I am working on a project to for us to produce these faster and accurate. Closing out for now.
