### ISSUE TITLE
ZX Sensor missing?

### ISSUE THREAD

**Issue by blundell** [sparkfun/Fritzing_Parts#21]
https://learn.sparkfun.com/tutorials/zx-distance-and-gesture-sensor-hookup-guide

![](https://cdn.sparkfun.com/r/600-600/assets/learn_tutorials/3/4/5/zx_sensor_fritzing_bb.png)

As you can see the doc here has a fritzing diagram, but then I can't find those parts (or the file anywhere) in your repo. Any ideas?

**Comment by ShawnHymel** [comment]
Here is the part I used for that diagram. Note that it's really just an image: there's no schematic, PCB, or metadata filled in. [ZX Sensor_fritzing.zip](https://github.com/sparkfun/Fritzing_Parts/files/1188539/ZX.Sensor_fritzing.zip)
