### ISSUE TITLE
Missing TMP006 part

### ISSUE THREAD

**Issue by rogeriobiondi** [sparkfun/Fritzing_Parts#22]
Hello,

I'm trying to sketch my project in Fritzing but it's missing the TMP006 part. May you help me, please?

Thank you very much.

Best regards

**Comment by loricrotser** [comment]
This product has been retired - we have an updated version; the TMP102. It is located here: 
https://www.sparkfun.com/products/13314

The Fritzing part for the TMP102 is located in the SparkFun Fritzing_Parts directory located here: 
https://github.com/sparkfun/Fritzing_Parts

The part is 13314_sfe_digital_temperature_sensor_breakout-TMP102. 

Hope this helps!
