### ISSUE TITLE
ESP8266 Thing is missing some connectors

### ISSUE THREAD

**Issue by tom-mi** [sparkfun/Fritzing_Parts#24]
Hi,
I just noticed that the ESP8266 fritzing part is missing the RST pin and the (two?) DTR connectors.
The WIFI antenna connector would also be nice ...
(The dev board is also affected)
I tried to edit the schematics myself, but failed.

Please fix :)

**Comment by loricrotser** [comment]
Just re-generated the part and re-uploaded. The two missing through holes are now available for routing. The WIFI antenna connector comes through as an SMD part which is listed as unrouteable so we left it as is. 

https://github.com/sparkfun/Fritzing_Parts/blob/master/products/13231_sfe_esp8266_thing.fzpz
