### ISSUE TITLE
Missing license.txt!

### ISSUE THREAD

**Issue by majikthys** [sparkfun/Fritzing_Parts#25]
It's unclear what license the assets in this repository fall under, these images/fritzing diagrams are widely republished across the internet and it would be good to add an explicit copyleft license such as creative commons share-alike w/ attribution: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by loricrotser** [comment]
Hola! Fritzing parts fall under the creative commons license. I've added our standard SparkFun license file, which includes the CC license text. Thanks for the heads up here!
