### ISSUE TITLE
Missing Fritzing file for ZED-F9P breakout board (product #  GPS-15136)

### ISSUE THREAD

**Issue by benreu** [sparkfun/Fritzing_Parts#31]
Like the title says, it would be nice to have the Fritzing fzpz part for the F9P breakout board.

**Comment by benreu** [comment]
Here is a feeble attempt to create this part. The base was generated using Eagle to Fritzing software.

[ZED-F9P.zip](https://github.com/sparkfun/Fritzing_Parts/files/5818194/ZED-F9P.zip)

This file ending needs to be renamed to a .fzpz 
It can then be imported into Fritzing.

**Comment by bboyho** [comment]
Hi!

Another representative generated and edited the ZED-F9P as well. It has been pushed to the repo:

    https://github.com/sparkfun/Fritzing_Parts/blob/master/products/15136_sfe_Qwiic_GPS-RTK2_ublox_ZED-F9P.fzpz
