### ISSUE TITLE
Request: SparkFun Transceiver Breakout - MAX3232

### ISSUE THREAD

**Issue by rgov** [sparkfun/Fritzing_Parts#33]
Fritzing has an RS-232 transceiver, but the [SparkFun variant](https://www.sparkfun.com/products/11189) follows a much different layout.

**Comment by bboyho** [comment]
Hi!

Sorry, I just noticed this. I did create a Fritzing part recently from another recent request => https://github.com/sparkfun/MAX3232_Breakout/issues/1 . 

You can find this part right here => https://github.com/sparkfun/Fritzing_Parts/blob/main/products/11189-sfe_transceiver_breakout_max3232_rs232_converter_ttl.fzpz . 

=)
