### ISSUE TITLE
intel edison blocks

### ISSUE THREAD

**Issue by bewest** [sparkfun/Fritzing_Parts#5]
Howdy, it would be awesome to have the sparkfun intel edison blocks available in fritzing, especially your block template.  This could make new blocks, like including cc1111 or a wixel easier.  Thanks!

**Comment by mgrusin** [comment]
We'll certainly consider it, but as the board layout is quite challenging on these, I highly recommend learning Eagle and using the supplied hardware files for your new designs.

**Comment by bewest** [comment]
Thanks, I just found the https://github.com/sparkfun/Sparkfun_Blocks_Template and friends (I was ignorant of them when I filed the issue).  Thanks again.

**Comment by mgrusin** [comment]
No problem! Good luck and let us know if you have any questions.
