### ISSUE TITLE
Pull in Weather Shield Fritzing part

### ISSUE THREAD

**Issue by ToniCorinne** [sparkfun/Fritzing_Parts#7]
Pull into Fritzing library, and clean up from [Weather shield repo](https://github.com/sparkfun/Weather_Shield)

**Comment by el-j** [comment]
hej toni, 
we can bring the part to fritzing parts. but therefor the fzpz needs to be extracted and cleaned up to fit in the fritzing parts folder-structure.

**Comment by elizabethsrobert** [comment]
Weather Shield in Fritzing_Parts and Repo cleaned up
