### ISSUE TITLE
LM7805 swaps legs in PCB view

### ISSUE THREAD

**Issue by jenschr** [sparkfun/Fritzing_Parts#8]
Using the Sparkfun library part will give anyone using it a decent short. Using this part, it connects ground to VIN on my PCB. Using the generic TO220 piece, it's correct in both views. Please fix and pull into next version of Fritzing?

**Comment by elizabethsrobert** [comment]
Hi @jenschr! Do you have a specific board you are referring to?

**Comment by jenschr** [comment]
Know what? This was just me being stupid I think. I swapped the layers used for etching and that made it mirrored. Just ignore.
